In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [5]:
X.shape

(10000, 10)

In [6]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [7]:
labelencoder_X_1 = LabelEncoder()

In [8]:
X[:,1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [9]:
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

In [10]:
X[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [11]:
X[:,2] = labelencoder_X_1.fit_transform(X[:,2])

In [12]:
len(X[0])

10

In [13]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [16]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
X[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [18]:
len(X[0])

12

In [19]:
X = X[:,1:]

In [20]:
len(X[0])

11

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
X.shape,X_train.shape

((10000, 11), (8000, 11))

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc = StandardScaler()

In [25]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [26]:
X_train[0]

array([-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
        0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
        1.10643166])

In [27]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

Using Theano backend.


In [28]:
# Parameter Tuning
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    classifier.summary()
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.5511 - accuracy: 0.7958
Epoch 2/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4349 - accuracy: 0.7971
Epoch 3/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4299 - accuracy: 0.7971
Epoch 4/100
7200/7200 [==============================] - 0s 17us/step - lo

7200/7200 [==============================] - 0s 15us/step - loss: 0.4015 - accuracy: 0.8347
Epoch 73/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4017 - accuracy: 0.8346
Epoch 74/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4016 - accuracy: 0.8346
Epoch 75/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4016 - accuracy: 0.8342
Epoch 76/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4018 - accuracy: 0.8339
Epoch 77/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4019 - accuracy: 0.8350
Epoch 78/100
7200/7200 [==============================] - 0s 19us/step - loss: 0.4015 - accuracy: 0.8343
Epoch 79/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4014 - accuracy: 0.8343
Epoch 80/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4013 - accuracy: 0.8346
Epoch 81/100
7200/7200 [==============================] - 0s 15us/st

7200/7200 [==============================] - 0s 16us/step - loss: 0.4017 - accuracy: 0.8356
Epoch 44/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4014 - accuracy: 0.8354
Epoch 45/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4016 - accuracy: 0.8358
Epoch 46/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4014 - accuracy: 0.8368
Epoch 47/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4014 - accuracy: 0.8349
Epoch 48/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4013 - accuracy: 0.8350
Epoch 49/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4009 - accuracy: 0.8351
Epoch 50/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4010 - accuracy: 0.8356
Epoch 51/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4013 - accuracy: 0.8357
Epoch 52/100
7200/7200 [==============================] - 0s 16us/st

7200/7200 [==============================] - 0s 15us/step - loss: 0.4131 - accuracy: 0.8326
Epoch 15/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4120 - accuracy: 0.8319
Epoch 16/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4117 - accuracy: 0.8342
Epoch 17/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4111 - accuracy: 0.8344
Epoch 18/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4104 - accuracy: 0.8342
Epoch 19/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4100 - accuracy: 0.8336
Epoch 20/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4094 - accuracy: 0.8338
Epoch 21/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4089 - accuracy: 0.8340
Epoch 22/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4086 - accuracy: 0.8346
Epoch 23/100
7200/7200 [==============================] - 0s 19us/st

7200/7200 [==============================] - 0s 14us/step - loss: 0.4004 - accuracy: 0.8339
Epoch 93/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4005 - accuracy: 0.8358
Epoch 94/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4008 - accuracy: 0.8358
Epoch 95/100
7200/7200 [==============================] - 0s 13us/step - loss: 0.4010 - accuracy: 0.8344
Epoch 96/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4003 - accuracy: 0.8344
Epoch 97/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4005 - accuracy: 0.8361
Epoch 98/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4004 - accuracy: 0.8354
Epoch 99/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4006 - accuracy: 0.8344
Epoch 100/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4004 - accuracy: 0.8354
Model: "sequential_4"
_____________________________________________

7200/7200 [==============================] - 0s 14us/step - loss: 0.3993 - accuracy: 0.8358
Epoch 64/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3988 - accuracy: 0.8363
Epoch 65/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.3988 - accuracy: 0.8357
Epoch 66/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.3989 - accuracy: 0.8356
Epoch 67/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3988 - accuracy: 0.8357
Epoch 68/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.3988 - accuracy: 0.8367
Epoch 69/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.3986 - accuracy: 0.8357
Epoch 70/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3986 - accuracy: 0.8354
Epoch 71/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.3992 - accuracy: 0.8365
Epoch 72/100
7200/7200 [==============================] - 0s 15us/st

7200/7200 [==============================] - 0s 13us/step - loss: 0.4082 - accuracy: 0.8356
Epoch 34/100
7200/7200 [==============================] - 0s 13us/step - loss: 0.4082 - accuracy: 0.8350
Epoch 35/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4081 - accuracy: 0.8347
Epoch 36/100
7200/7200 [==============================] - 0s 13us/step - loss: 0.4078 - accuracy: 0.8324
Epoch 37/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4075 - accuracy: 0.8344
Epoch 38/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4073 - accuracy: 0.8358
Epoch 39/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4070 - accuracy: 0.8347
Epoch 40/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4069 - accuracy: 0.8333
Epoch 41/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4061 - accuracy: 0.8342
Epoch 42/100
7200/7200 [==============================] - 0s 15us/st

7200/7200 [==============================] - 0s 14us/step - loss: 0.4187 - accuracy: 0.8232
Epoch 5/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4142 - accuracy: 0.8258
Epoch 6/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4107 - accuracy: 0.8289
Epoch 7/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4080 - accuracy: 0.8294
Epoch 8/100
7200/7200 [==============================] - 0s 18us/step - loss: 0.4062 - accuracy: 0.8292
Epoch 9/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4048 - accuracy: 0.8308
Epoch 10/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4038 - accuracy: 0.8311
Epoch 11/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4028 - accuracy: 0.8332
Epoch 12/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4021 - accuracy: 0.8324
Epoch 13/100
7200/7200 [==============================] - 0s 14us/step - 

7200/7200 [==============================] - 0s 16us/step - loss: 0.3914 - accuracy: 0.8371
Epoch 83/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3914 - accuracy: 0.8379
Epoch 84/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3907 - accuracy: 0.8388
Epoch 85/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3908 - accuracy: 0.8374
Epoch 86/100
7200/7200 [==============================] - 0s 18us/step - loss: 0.3901 - accuracy: 0.8375
Epoch 87/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.3897 - accuracy: 0.8378
Epoch 88/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3894 - accuracy: 0.8382
Epoch 89/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3887 - accuracy: 0.8394
Epoch 90/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3882 - accuracy: 0.8401
Epoch 91/100
7200/7200 [==============================] - 0s 15us/st

7200/7200 [==============================] - 0s 15us/step - loss: 0.4017 - accuracy: 0.8360
Epoch 54/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4018 - accuracy: 0.8354
Epoch 55/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4018 - accuracy: 0.8361
Epoch 56/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4018 - accuracy: 0.8363
Epoch 57/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4013 - accuracy: 0.8356
Epoch 58/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4014 - accuracy: 0.8351
Epoch 59/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4015 - accuracy: 0.8367
Epoch 60/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4015 - accuracy: 0.8356
Epoch 61/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4011 - accuracy: 0.8357
Epoch 62/100
7200/7200 [==============================] - 0s 15us/st

7200/7200 [==============================] - 0s 16us/step - loss: 0.4031 - accuracy: 0.8371
Epoch 25/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4033 - accuracy: 0.8358
Epoch 26/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4029 - accuracy: 0.8364
Epoch 27/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4024 - accuracy: 0.8368
Epoch 28/100
7200/7200 [==============================] - 0s 19us/step - loss: 0.4021 - accuracy: 0.8351
Epoch 29/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4021 - accuracy: 0.8358
Epoch 30/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4020 - accuracy: 0.8364
Epoch 31/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4019 - accuracy: 0.8358
Epoch 32/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4014 - accuracy: 0.8358
Epoch 33/100
7200/7200 [==============================] - 0s 16us/st

dense_25 (Dense)             (None, 6)                 72        
_________________________________________________________________
dense_26 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_27 (Dense)             (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.5498 - accuracy: 0.7956
Epoch 2/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4291 - accuracy: 0.7957
Epoch 3/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4239 - accuracy: 0.7957
Epoch 4/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.4223 - accuracy: 0.7957
Epoch 5/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4208 - accuracy: 0.7957
Epoch 6/100
7200/720

7200/7200 [==============================] - 0s 17us/step - loss: 0.3974 - accuracy: 0.8354
Epoch 75/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.3975 - accuracy: 0.8376
Epoch 76/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3974 - accuracy: 0.8376
Epoch 77/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3975 - accuracy: 0.8383
Epoch 78/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3973 - accuracy: 0.8367
Epoch 79/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3976 - accuracy: 0.8349
Epoch 80/100
7200/7200 [==============================] - 0s 15us/step - loss: 0.3970 - accuracy: 0.8360
Epoch 81/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3973 - accuracy: 0.8369
Epoch 82/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.3972 - accuracy: 0.8369
Epoch 83/100
7200/7200 [==============================] - 0s 17us/st

7200/7200 [==============================] - 0s 17us/step - loss: 0.4057 - accuracy: 0.8346
Epoch 46/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4055 - accuracy: 0.8339
Epoch 47/100
7200/7200 [==============================] - 0s 18us/step - loss: 0.4053 - accuracy: 0.8339
Epoch 48/100
7200/7200 [==============================] - 0s 17us/step - loss: 0.4053 - accuracy: 0.8336
Epoch 49/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4054 - accuracy: 0.8329
Epoch 50/100
7200/7200 [==============================] - 0s 16us/step - loss: 0.4050 - accuracy: 0.8349
Epoch 51/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4051 - accuracy: 0.8325
Epoch 52/100
7200/7200 [==============================] - 0s 14us/step - loss: 0.4048 - accuracy: 0.8336
Epoch 53/100
7200/7200 [==============================] - 0s 19us/step - loss: 0.4052 - accuracy: 0.8346
Epoch 54/100
7200/7200 [==============================] - 0s 16us/st

KeyboardInterrupt: 